name: aerospike-console
dir: src/github.com/citrusleaf/amc

container:
  - base:
      - docker.qe.aerospike.com/build/golang:1.7

environment:
  GOPATH: /work/source
  BIN: $GOPATH/bin
  REPO: github.com/citrusleaf/amc
  CGO_ENABLED: 1

build:
  - name: default
    script:
      - echo $PWD
      - $REPO/make.sh enterprise prod linux
      - $REPO/make.sh community prod linux
      - $REPO/make.sh enterprise prod darwin
      - $REPO/make.sh community prod darwin
    artifact:
      - aerospike-amc-*.deb
      - aerospike-amc-*.rpm
