name: aerospike-console
dir: src/github.com/aerospike-community/amc

container:
  - base:
      - docker.qe.aerospike.com/build/amc:golang-1.11

environment:
  GOPATH: /work/source
  BIN: $GOPATH/bin
  REPO: github.com/aerospike-community/amc
  CGO_ENABLED: 0

build:
  - name: default
    script:
      - ls -la
      - cd src/$REPO
      - ./make.sh enterprise prod linux
      - ./make.sh community prod linux
      - ./make.sh enterprise prod darwin
      - ./make.sh community prod darwin
    artifact:
      - aerospike-amc-*.deb
      - aerospike-amc-*.rpm
      - aerospike-amc-*.gz
